# Header
menu:
  首页: /
  归档: /archives
  关于: /about

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  主题作者: http://xiguabaobao.com
  热前端: http://reqianduan.com

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
#duoshuo: 
#  enable: true  ## duoshuo.com
#  short_name:    ##e.g. wuchong   for duoshuo short name.
# Disqus
disqus_shortname:  funglau

# Baidu share
baidushare: true